import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { API_URL } from '@/utils/constants';
import { fetchUsersData } from '@/redux/actions/shared';
import Loader from '@/components/Loader';
import StyledLayout from '@/components/StyledLayout';
import Users from '@/components/Users';

export default function Home() {
  const dispatch = useDispatch();
  const users = useSelector((state) => state.users.users);
  const isLoading = useSelector((state) => state.users.isLoading);
  const error = useSelector((state) => state.users.error);

  const fetchUsers = () => {
    const getUsersAPI = `${API_URL.USERS}`;
    dispatch(fetchUsersData(getUsersAPI));
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  if (isLoading) {
    return (
      <StyledLayout>
        <Loader />
      </StyledLayout>
    );
  }

  if (error) {
    return <p>Error: {error}</p>;
  }

  return (
    <>
      <Head>
        <title>Profiles List | NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StyledLayout>
          <Users users={users} />
        </StyledLayout>
      </main>
    </>
  );
}
